version: '2'
services:
    invest-app:
        image: invest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://invest-postgresql:5432/invest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    invest-postgresql:
        extends:
            file: postgresql.yml
            service: invest-postgresql
