version: '2'
services:
    invest-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/invest/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=invest
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
